openapi: 3.0.0
servers:
  - url: http://localhost:8080/api/v1
info:
  title: Nazo Playground API
  version: 0.1.0
tags:
  - name: nazo
paths:
  /nazo:
    $ref: paths/nazo.yaml
  /nazo/{id}:
    $ref: paths/nazo@{id}.yaml
  /nazo/{id}/answer:
    $ref: paths/nazo@{id}@answer.yaml
